format = """\
[â•­â•´](fg:arrow)\
$os\
$directory\
(\
    $git_branch\
    $git_status\
)\
$cmd_duration\
$fill\
[ $time](fg:text_color)\
[ $battery](fg:text_color)\
[ $java](fg:text_color)\
[ $nodejs](fg:text_color)\
[ $python](fg:text_color)\
[ $conda](fg:text_color)\
[ $rust](fg:text_color)\
[ $golang](fg:text_color)\
[ $bun](fg:text_color)\
[ $docker_context](fg:text_color)
[â•°â”€](fg:arrow)$character"""

add_newline = true

palette = "old"

[palettes.old]
arrow = "#353535"
os = "#3778BF"
os_admin = "#6A040F"
directory = "#3F37C9"
node = "green"
time = "#177E89"
git = "#B02B10"
git_status = "#8B1D2C"
python = "#3776AB"
conda = "#3EB049"
java = "#861215"
rust = "#C33C00"
clang = "#00599D"
duration = "#3D3D3D"
text_color = "#EDF2F4"
text_light = "#EDF2F4"

[palettes.normal]
arrow = "#353535"
os = "#2C3032"
os_admin = "#6A040F"
directory = "#363C3E"
time = "#474D5C"
node = "#F1DEA9"
git = "#D0DBDA"
git_status = "#DFEBED"
python = "#F5CB5C"
conda = "#3EB049"
java = "#861215"
rust = "#C33C00"
clang = "#00599D"
duration = "#F4FBFF"
text_color = "#EDF2F4"
text_light = "#26272A"

[palettes.light]
arrow = "#353535"
os = "#F7768E"
os_admin = "#ACBEF1"
directory = "#FF9578"
time = "#FFDC72"
git = "#F5F5F5"
git_status = "#72FFD5"
clang = "#67E3FF"
java = "#FF52A3"
python = "#B4F9F8"
node = "#81FF85"
conda = "#BAF5C0"
duration = "#91FFE7"
text_color = "#26272A"
text_light = "#26272A"

[username]
style_user = 'os'
style_root = 'os_admin'
format = '[î‚¶]($style)[ï…º  mou](bg:$style fg:text_color)[î‚´]($style)'
disabled = false
show_always = true

[character]
success_symbol = "[ó°Ÿ](fg:arrow)"
error_symbol = "[ó°Ÿ](fg:red)"

[directory]
format = " [î‚¶](fg:directory)[ï¼  $path ]($style)[$read_only]($read_only_style)[î‚´](fg:directory)"
truncation_length = 2
style = "fg:text_color bg:directory"
read_only_style = "fg:text_color bg:directory"
before_repo_root_style = "fg:text_color bg:directory"
truncation_symbol = "â€¦/"
truncate_to_repo = true
read_only =" î©µ "

[time]
disabled = false
format = " [î‚¶](fg:time)[ï€— $time]($style)[î‚´](fg:time)"
time_format = "%H:%M"
style = "fg:text_color bg:time"

[cmd_duration]
format = " [î‚¶](fg:duration)[ï‰” $duration]($style)[î‚´](fg:duration)"
style = "fg:text_light bg:duration"
min_time = 500

[fill]
symbol = " "

[git_branch]
format = " [î‚¶](fg:git)[$symbol$branch](fg:text_light bg:git)[î‚´](fg:git)"
symbol = "ï˜ "

[git_status]
format = '([ î‚¶](fg:git_status)[ $all_status$ahead_behind ]($style)[î‚´](fg:git_status))'
style = "fg:text_light bg:git_status"

[docker_context]
disabled=true
symbol = "ïŒˆ "

[package]
disabled=true

[java]
format = "[ î‚¶](fg:java)[$symbol$version](bg:java fg:text_color)[î‚´](fg:java)"
version_format = "${raw}"
symbol = "î‰– "
disabled = false

[nodejs]
format = "[ î‚¶](fg:node)[$symbol$version]($style)[î‚´](fg:node)"
style = "bg:node fg:text_light"
symbol = "îœ˜ "
version_format = "${raw}"
disabled = false

[rust]
format = "[ î‚¶](fg:rust)[$symbol$version](bg:rust fg:text_color)[î‚´](fg:rust)"
symbol = "îš‹ "
version_format = "${raw}"
disabled = false

[python]
disabled = false
format = '[ î‚¶](fg:python)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[î‚´](fg:python)'
symbol = "î˜† "
version_format = "${raw}"
style = "fg:text_light bg:python"

[conda]
format = "[ î‚¶](fg:conda)[$symbol$environment]($style)[î‚´](fg:conda)"
style = "bg:conda fg:text_color"
ignore_base = false
disabled = false
symbol = "ï„Œ "

[golang]
format = "[ î‚¶](fg:clang)[$symbol($version(-$name) )](bg:clang fg:text_color)[î‚´](fg:clang)"
symbol = "î˜ "
version_format = "${raw}"
disabled = false

[bun]
format = "[ î‚¶](fg:#F9F1A5)[$symbol$version](bg:#F9F1A5 fg:text_color)[î‚´](fg:#F9F1A5)"
symbol = "ğŸ«“ "
version_format = "${raw}"
disabled = false

[battery]
full_symbol = "ó°¹ "
charging_symbol = "ó°¢ "
discharging_symbol = "ó°¼ "
unknown_symbol = "ó°‚‘ "
empty_symbol = "ó°‚ "
disabled = false
format = "[$symbol$percentage]($style)"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[os]
disabled = false
format = "[ î‚¶](fg:os)[$symbol](bg:os fg:text_color)[î‚´](fg:os)"

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "ï…»"
Arch = "ïŒƒ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "îŠ"
Emscripten = "ïˆ…"
EndeavourOS = "ï†—"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Gentoo = "ïŒ"
Linux = "ïŒš"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Mariner = "ï‡"
MidnightBSD = "ï††"
Mint = "ïŒ"
NetBSD = "ï€¤"
NixOS = "ïŒ“"
openSUSE = "ïŒ”"
Pop = "îŠ£"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Redox = "ï”—"
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ïˆ­"
Windows = "ï…º"
